config/routes.rb
Rails.application.routes.draw do

  
  devise_for :users, :controllers => {
    :registrations => "users/registrations",
  }
  resources :cases
  resources :admin
  resources :infos
  root 'cases#index'
 
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/admin/edit.html.erb
<div class = "container">
  <h1>Edit</h1>

  <br>

  <%= form_with(model: @user, local: true, url: admin_path(@user)) do |form| %>
    <% if @user.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@user.errors.count, "error") %> prohibited this @user from being saved:</h2>

        <ul>
          <% @user.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="shadow-none p-3 mb-5 bg-light rounded">
      <div class="field">
        <%= form.label :id %><br>
        <%= form.text_field :id %>
      </div>

      <br>

      <div class="field">
        <%= form.label :name %><br>
        <%= form.text_field :name %>
      </div>

      <br>

      <div class="field">
        <%= form.label :email %><br>
        <%= form.text_field :email %>
      </div>
    </div>

    <br>

    <div class="actions">
      <%= form.submit(class: 'btn btn-secondary') %>
    </div>
  <% end %>
</div>

app/views/admin/index.html.erb
<h1>Admin</h1>

<br>

<table class="table">
  <thead>
    <tr>
      <th>ID</th>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>  
    <% @users.each do |user| %>
      <tr>
          <td><%= user.id %></td>
          <td><%= user.name %></td>
          <td><%= user.email %></td>
          <td><%= link_to 'Show', admin_path(user) %></td>
        
        <% if user_signed_in? %>
          <td><%= link_to 'Edit', edit_admin_path(user) %></td>
          <td><%= link_to 'Destroy', admin_path(user), method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>

  </tbody>

</table>

app/views/admin/show.html.erb
<div class = "container">
  <h1>Show</h1>

  <br>

  <p id="notice"><%= notice %></p>

  <div class="shadow-none p-3 mb-4 bg-light rounded">
    <p>
      <strong>ID:</strong><br>
      <%= @user.id %>
    </p>

    <p>
      <strong>Name:</strong><br>
      <%= @user.name %>
    </p>

    <p>
      <strong>Email:</strong><br>
      <%= @user.email %>
    </p>
  </div>


  <button type="button" class="btn btn-outline-primary"><%= link_to 'Edit', edit_admin_path(@user) %></button>
  <button type="button" class="btn btn-outline-primary"><%= link_to 'Back', admin_index_path %></button>
</div>