config/routes.rb
Rails.application.routes.draw do

  
  devise_for :users, :controllers => {
    :registrations => "users/registrations",
  }
  resources :cases
  resources :admin
  resources :infos
  root 'cases#index'
 
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/info.rb
class Info < ApplicationRecord
end

app/controllers/infos_controller.rb
class InfosController < ApplicationController
  before_action :set_info, only: [:show, :edit, :update, :destroy]

  def index
    @infos = Info.all.order(created_at: 'desc')
  end

  def show
  end

  def new
    @info = Info.new
  end

  def edit
  end

  def create
    @info = Info.new(info_params)

    respond_to do |format|
      if @info.save
        format.html { redirect_to @info, notice: 'Info was successfully created.' }
        format.json { render :show, status: :created, location: @info }
      else
        format.html { render :new }
        format.json { render json: @info.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @info.update(info_params)
        format.html { redirect_to @info, notice: 'Info was successfully updated.' }
        format.json { render :show, status: :ok, location: @info }
      else
        format.html { render :edit }
        format.json { render json: @info.errors, status: :unprocessable_entity }
      end
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_info
    @info = Info.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def info_params
    params.require(:info).permit(:title, :memo)
  end
end

app/helpers/infos_helper.rb
module InfosHelper
end

app/views/infos/edit.html.erb
<div class = "container">
  <h1>Edit</h1>

  <br>

  <%= form_with(model: @info, local: true) do |form| %>
    <% if @info.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@info.errors.count, "error") %> prohibited this @info from being saved:</h2>

        <ul>
          <% @info.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="shadow-none p-3 mb-5 bg-light rounded">
      <div class="field">
        <%= form.label :title %><br>
        <%= form.text_field :title %>
      </div>

      <br>

      <div class="field">
        <%= form.label :memo %><br>
        <%= form.text_area :memo %>
      </div>

    </div>

      <div class="actions">
        <%= form.submit(class: 'btn btn-secondary') %>
      </div>
  
  <% end %>
</div>

app/views/infos/index.html.erb
<div class = "container">

  <h2>Info</h2>

  <br>

  <div class="shadow p-3 mb-5 bg-white rounded">
    <ul>
      <% @infos.each do |info| %>
        <li>
        <%= link_to info.title, info_path(info) %>
        </li>
      <% end %>
    </ul>
  </div>

    <% if user_signed_in? %>
    <button type="button" class="btn btn-outline-primary"><%= link_to 'add new', new_info_path %></button>
    <% end %>
</div>

app/views/infos/new.html.erb
<div class = "container">
  <h2>Add New Info</h2>

  <br>

  <%= form_with(model: @info, local: true) do |form| %>
    <% if @info.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@info.errors.count, "error") %> prohibited this @info from being saved:</h2>

        <ul>
          <% @info.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="shadow-none p-3 mb-5 bg-light rounded">
      <div class="field">
        <%= form.label :title %><br>
        <%= form.text_field :title %>
      </div>

      <br>

      <div class="field">
        <%= form.label :memo %><br>
        <%= form.text_area :memo %>
      </div>
    </div>

    <div class="actions">
      <%= form.submit(class: 'btn btn-secondary') %>
    </div>
  <% end %>
</div>

app/views/infos/show.html.erb
<div class = "container">
  <h2>Show</h2>

  <br>

  <div class="shadow-none p-3 mb-4 bg-light rounded">
    <p>
      <strong>Title:</strong><br>
      <%= @info.title %>
    </p>

    <p>
      <strong>Post:</strong><br>
      <%= @info.memo %>
    </p>

    <p>
      <strong>Create:</strong><br>
      <%= @info.created_at %>
    </p>
  </div>

  <% if user_signed_in? %>
   <button type="button" class="btn btn-outline-primary"><%= link_to 'Edit', edit_info_path(@info) %></button> 
  <% end %>

  <button type="button" class="btn btn-outline-primary"><%= link_to 'Back', infos_path %></button> 
</div>