config/routes.rb
Rails.application.routes.draw do

  
  devise_for :users, :controllers => {
    :registrations => "users/registrations",
  }
  resources :cases
  resources :admin
  resources :infos
  root 'cases#index'
 
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html>
  <head>
    <title>TaskApp</title>
      <%= csrf_meta_tags %>

      <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
      <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    
    <nav class="navbar navbar-dark bg-dark">
    <!-- Navbar content -->
      <div class = "container">
        <header>
					<% if user_signed_in? %>
						<ul>
                <strong><%#= link_to current_user.username, cases_path %></strong>
                <li class="menue"><%= link_to 'プロフィール変更', edit_user_registration_path %></li>
                <li class="menue"><%= link_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
          <% else %>
						    <li class="menue"><%= link_to 'サインアップ', new_user_registration_path %></li>
						    <li class="menue"><%= link_to 'ログイン', new_user_session_path %></li>
          <% end %>

						    <li class="menue"><%= link_to 'case', cases_path %></li>
          <% if user_signed_in? %>
						    <li class="menue"><%= link_to 'admin', admin_index_path %></li>
          <% end %>
						    <li class="menue"><%= link_to 'info', infos_path %></li>
        </header>

            <p class="notice"><%= notice %></p>
						<p class="alert"><%= alert %></p>
			</div>
    </nav>
   <%= yield %>
  </body>
</html>